# .readthedocs.yml

# The version of the configuration file format (Read the Docs version 2)
version: 2

# The name of the MkDocs configuration file
mkdocs:
  configuration: mkdocs.yml  # This links to your mkdocs.yml file

# Python requirements file location
python:
  install:
    - requirements: docs/requirements.txt  # Path to your requirements.txt file

# Build settings
build:
  os: ubuntu-22.04  # You can change this to another version if needed
  tools:
    python: "3.12"  # Python version to use for building docs

# Optional: You can specify any extra configurations here if needed

# Read the Docs configuration
